---
title: "Product SHORT NAME Product User Manual (PUM)"
subtitle: "PUM Copernicus Land Monitoring Service - Product full name"
date: "2022-10-06"
version: Issue x.y (“(x) version of the document” + “.”+ “(y) version of the document
  update”) (first published version must start with 1.0)
template-version: 1.0.0
product-name: Product Name
description: "Product DESCRIPTION"

metadata-files:
- ../../metadata/default.yml

format:
  html:
    css: ../styles/styles.css
  docx:
    reference-doc: ../styles/template-pum.docx
    hidden: true
  pdf: default
---

{{< pagebreak >}}

::: {.subtitle custom-style="subtitle"}
CLMS Algorithm Theoretical Basis Document Template
\
\
\
IMPORTANT: Please read this section then delete before submitting your report.
\
:::

# How to use the CLMS Product User Manual template {.unnumbered .unlisted}

This is the Product User Manual (PUM) template. You should use it to write the PUM reports for the Copernicus Land Monitoring Service. The template provides the structure and guidelines as you develop your report.

For more information about the design and style, please refer to the "CLMS Word template CLMS_February" and the CLMS Brand Guidelines or contact the communications team at the EEA.

The PUM template is organised into a set of chapters and subchapters that may be mandatory or optional. Each section is clearly identified as either (mandatory) or (optional).

You may insert a new subchapter (not described in the current structure) if you deem it necessary.

If any of the mandatory sections of the PUM cannot be described or are not applicable, please include a statement in the corresponding section explaining the reason.

The PUM template contains the following information:

-   The structure of chapters and subchapters that must be used when editing the report.

-   Information for internal project use only that must be deleted before the product is published. This information is presented in [blue boxes]{.blue-box custom-style="blue-box-line"}.

-   Instructions (e.g. an overview of the content that should be followed when editing the section). This information is presented in [yellow boxes]{.yellow-box custom-style="yellow-box-line"} and must be deleted and replaced with your content (e.g. text, tables, figures).

-   Examples of standard text and tables for chapters or subchapters (these examples are presented in [grey boxes]{.grey-box custom-style="grey-box-line"}) that can be adapted accordingly.

For visual insets such as charts, graphs, diagrams, tables, maps and photos, follow these guidelines:

-   Assign each inset a numbered caption with a clear and descriptive title (follow the design and style instructions given in the "CLMS Word template CLMS_February").Use automatic numbering for insets, to ensure that insets are numbered sequentially in **bold** (e.g., **Figure 1**, **Table 1**).

-   In the body text, refer to the inset\'s caption number in **bold**, explaining the visual\'s content (e.g., "As shown in **Inset 1**, the data highlights the following trend..."). Always use Word's cross-reference tool for referencing insets, ensuring that references update automatically if numbers change.

A guide on best practices and principles for data visualisation, is available at the URL \"<https://data.europa.eu/apps/data-visualisation-guide/>\".

# End of instructions. Delete up to here. {.unnumbered .unlisted}

:::{.blue-box custom-style="blue-box"}
The document information presented in this page is only for internal project use and **MUST BE DELETED BEFORE THE PRODUCT IS PUBLISHED!**
:::

## Document control information: (internal project use) {.unnumbered .unlisted .blue-box}

:::{.blue-box custom-style="blue-box"}
Details about the management and oversight of the document, including version control, document identifiers, and distribution lists.

  -------------------------------------------------------------------------------------------------
  Document Title                      Dx.y Product User Manual
  ----------------------------------- -------------------------------------------------------------
  Project Title                       Copernicus Land Monitoring Service -- "name of the product"

  Document Author                     Name (Entity)

  Project Owner                       Name (Entity)

  Project Manager                     Name (Entity)

  Document Code                       Dx.y

  Document Version                    x.y

  Distribution                        Parties to whom the document is provided
  -------------------------------------------------------------------------------------------------
:::

## Document approver(s) and reviewer(s): (internal project use) {.unnumbered .unlisted .blue-box}

:::{.blue-box custom-style="blue-box"}
Names and roles of individuals who have reviewed and approved the document, ensuring its accuracy, completeness, and compliance with relevant standards.

  -----------------------------------------------------------------------
  Name              Role              Action            Date
  ----------------- ----------------- ----------------- -----------------
                    Author                              dd.mm.yyyy

                    Review                              dd.mm.yyyy

                    Approval                            dd.mm.yyyy
  -----------------------------------------------------------------------
  
:::

## Document history: (internal project use) {.unnumbered .unlisted}

:::{.blue-box custom-style="blue-box"}
Record of changes made to the document **before the initial published version**, including version numbers, dates of revisions, and a summary of modifications.

  -----------------------------------------------------------------------------------------------
  Version       Date         Created by         Short description of changes
  ------------- ------------ ------------------ -------------------------------------------------
  0.1           dd.mm.yyyy                      Initial draft

  0.2           dd.mm.yyyy                      Content revisions (e.g., structure, formatting)

  0.3           dd.mm.yyyy                      Minor revisions (e.g., grammar fixes)
  -----------------------------------------------------------------------------------------------

:::
## Document history:{.unnumbered .unlisted}

:::{.grey-box custom-style="grey-box"}
Record of changes made to the document over time **after the initial published version**, including version numbers, dates of revisions, and a summary of modifications. This table must be only included in the **initial PUM published version** and without the personal information ("Created by:" filed must be removed).

  --------------------------------------------------------------------------
  Version       Date         Short description of changes
  ------------- ------------ -----------------------------------------------
  1.0           dd.mm.yyyy   Initial published issue

  1.1           dd.mm.yyyy   Minor revisions (e.g., grammar fixes)

  x.y           dd.mm.yyyy   ...
  --------------------------------------------------------------------------


:::
{{< pagebreak >}}


# Non-technical summary [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents a simplified explanation of the main topics for a non-expert audience, making the information accessible and understandable to the general public by using clear language, focusing on the key points and overall significance, and avoiding technical jargon.

A well-crafted non-technical summary should effectively describe the CLMS product to both the public and researchers or users who are non-specialists in your field. To achieve this, consider the following suggestions:

1.  **Know the audience**: The goal is to make the CLMS product understandable and engaging to someone without specialized knowledge.

2.  **Be specific and clear**: Avoid vague statements and use clear and concise language that directly conveys your message.

3.  **Be clear and concise**: Use short, simple words and sentences, aiming for everyday language keeping sentences under 25 words whenever possible. This non-technical summary should not exceed one page.

4.  **Provide context**: Use concrete examples to help illustrate your points and create a vivid picture for the reader.

5.  **Use active voice**: Focus on what you are doing rather than what will be done.

6.  **Limit acronyms and abbreviations**: Avoid using them as much as possible.

7.  **Avoid technical jargon**: Steer clear of phrases common in report writing (e.g., moreover, therefore).

8.  **Create original content**: Rather than copying and pasting from the main text, use the suggested headings to organize the summary clearly and accessible to all readers.

9.  **Be concise**: Strive to maintain a length of 350--400 words, focusing on the core message.

For guidance take note of these external references:

-   <https://www.understandinganimalresearch.org.uk/application/files/5516/5226/6818/Writing_NTS_summaries.pdf>

-   <https://publications.europa.eu/resource/cellar/2b399830-cb4b-11e7-a5d5-01aa75ed71a1.0001.03/DOC_1>

-   <https://communications.admin.ox.ac.uk/resources/how-to-guide-writing-a-lay-summary>

Here is an exercise for creating a non-technical summary of the executive summary contained in **[Product user manual -- DLT, FT and TCD 2018 and DLT, FT and TCD Changes](https://land.copernicus.eu/en/technical-library/hrl-forest-2018/@@download/file):**
:::

::: {.grey-box custom-style="grey-box"}
The **Copernicus High-Resolution Layer Forest 2018** is a product developed to map and monitor forest areas across Europe and it is part of the European Union's Earth observation program.

This product uses satellite data to map tree cover and detect changes in forests between 2015 and 2018. It plays a critical role in environmental monitoring, policymaking, and forest management.

**Product key Features:**

-   **Tree Cover Density**: A map providing information about the tree coverage, measured in percentages. This helps users understand forest density across different regions.

-   **Dominant Leaf Type**: A dataset that classifies forests based on tree type, either broadleaved or coniferous. This helps in understanding forest composition and its environmental impacts.

-   **Forest Type**: Using international definitions, this dataset categorizes areas into forest and non-forest, such as urban parks or agricultural lands.

-   **Change Detection**: A map that shows where tree cover has increased or decreased between 2015 and 2018. This helps identify deforestation, reforestation, and forest degradation.

**Why is this product important?** It provides accurate, detailed data for environmental research, forest management, and policymaking. It is especially useful for monitoring biodiversity and climate change impacts.

This product also supports reports required by international organizations, including the United Nations and the European Union. It helps governments and organizations make informed decisions to protect ecosystems.

**Who can use it?** This information is available to a wide range of users, including environmental agencies, scientists, policymakers, and conservationists.

The data is openly accessible and can be used for research, policy reporting, and practical forest management tasks, like planning timber harvests or protecting forested areas from degradation.
:::

{{< pagebreak >}}

# Executive summary [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents an overview of the product, including purpose and main features.

An executive summary should concisely communicate the key points of the CLMS product to decision-makers and stakeholders. It should provide an overview of the CLMS, highlight the products layers and related products, and summarise the information presented in the PUM, including its relevance to the user community. To achieve this, consider the following suggestions:

1.  **Know the audience**: Write with executives and stakeholders in mind. Focus on what they need to know to make informed decisions and avoid unnecessary details.

2.  **Highlight key points**: Clearly summarize the most important aspects of the product, including objectives, key findings, and recommendations, being direct and to the point.

3.  **Be clear and concise**: Use straightforward language, aiming for sentences to be no longer than 25 words whenever possible. This executive summary should not exceed two pages.

4.  **Prioritize Information**: Lead with the most critical information and ensure that the most important details are easily accessible. Use bullet points or subheadings to break down complex information.

5.  **Use active voice**: Make your writing more engaging by using active voice. Focus on actions and outcomes, emphasizing what has been done and what is recommended.

6.  **Minimize jargon**: Use technical terms only when necessary, and ensure they are clearly explained, and avoid industry-specific jargon that might be unfamiliar to a broader audience.

:::

{{< pagebreak >}}

# Scope of the document [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Explains the primary purpose and coverage of the document.

Here an example:
:::

:::{.grey-box custom-style="grey-box"}
This Product User Manual is the primary document users should consult before using the product. It describes the product\'s characteristics, its purpose and lineage, and summarizes the production workflows. Additionally, it provides details on the terms of use and technical support for the product.
:::

:::{.yellow-box custom-style="yellow-box"}
Outlines the document\'s structure, including chapters on product descriptions, quality, access, and references.

In detail, the document is structured as follows:
:::

:::{.grey-box custom-style="grey-box"}

-   Chapter 1 provides the non-technical summary with a generic overview of the product, general information about European Union\'s Earth Observation Programme and Copernicus Land Monitoring Service (CLMS), who and why the product is used.

-   Chapter 2 provides the executive summary of the project along with a general information about European Union\'s Earth Observation Programme and CLMS.

-   Chapter 3 outlines the scope, content and structure of this document.

-   Chapter 4 introduces the initial objectives and user needs, and feedback collected.

-   Chapter 5 describes the current user requirements.

-   Chapter 6 presents potential application areas and example use cases.

-   Chapter 7 presents product description (product content and characteristics).

-   Chapter 8 summarizes the product methodology and workflow production.

-   Chapter 9 presents the terms of use, citation guidelines, and technical support for the product.

-   and the Abbreviations & Acronyms, References, FAQ's, and Annex Chapters provide citations, and supplementary information.

:::

{{< pagebreak >}}

# Lineage of product [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Discusses the initial objectives and user requirements of the product, summarizes current user needs and enhancement ideas, and compiles user requirements and feedback collected from surveys and studies.
:::

{{< pagebreak >}}

# User requirements [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Summarize the known current user needs. Where applicable, the review of user requirements for the product can reference topics such as:\"

-   Policy and monitoring support

-   Land cover and land use mapping

-   Data accessibility

-   Frequency and timeliness

-   Standardization and consistency

These user requirements could be summarized and presented as floating text within this chapter.
:::

{{< pagebreak >}}

# Product application areas and use case examples [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Outlines various use cases and potential application areas, as well as an overview of potential users. It details known and intended areas of application alongside documented use cases. Additionally, it provides guidance to users on known limitations, indicating scenarios where the product may not be suitable suggesting alternative products for such applications.
:::

{{< pagebreak >}}

# Product description [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Provides a comprehensive overview of the product, including all layers (where applicable). It details the layer's specifications, reference years or time series, and update cycles. Additionally, it outlines the thematic characteristics, geospatial format and distribution (e.g., 100 km LAEA tiles), as well as the metadata, standards, and alignment with the EEA reference grid. Ideally, exemplary tools for accessing and using the data are mentioned.
:::

## Overview of the product and contained layers [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Introduces the product (-suite) including the contained layers and their key features, components and the relation between them. The contained products/layers may be structured as needed. The suggestion is to use either separate third-level subchapters (i.e. 7.1.x) or any useful categorization () of contained products/layers without third-level subchapters.
:::

## Product characteristics [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Describes the characteristics of the product, the thematic definition and the relation with different products/layers, the elements included and excluded, classified features and the layer's coding. Use third-level subchapters to structure if needed.
:::

## Product specifications [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Details the description of each layer, including specific details about its resolution, accuracy, data type, other technical specifications, and geographic coverage. Use third-level subchapters to structure if needed.

The following tables shall be used as guidance to describe the layers specifications. Use separate tables for separate layers (if applicable).

Please note that:

-   If a field from Table 7.1 and Table 7.2 is not applicable, please insert the code \'NA\' in the content description. Tables should ideally be formatted to fit on one page.

-   Both Table 7.1 and Table 7.2 must fit on a single page. If any content descriptions are too lengthy and cause these tables to extend beyond one page (e.g., vector attributes), such content should be relocated to the annex section. References to this content must then be included in Table 7.1 and Table 7.2 accordingly.
:::
{{< pagebreak >}}

:::{.grey-box custom-style="grey-box"}

```{=html}
<table>
  <caption>Table 7.1 Vector product/layer sheet (replace with field ‘Layer name’)</caption>
  <thead>
    <tr>
      <th>Field</th>
      <th colspan="5">Content description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Layer name</td>
      <td colspan="5">Descriptive name of the layer (e.g., Urban Atlas Land Cover/Land Use 2021; CLCplus Backbone 2018 vector)</td>
    </tr>
    <tr>
      <td>Acronym</td>
      <td colspan="5">Abbreviation or shortened form of the layer name (align with file naming)</td>
    </tr>
    <tr>
      <td>Product (group/family)</td>
      <td colspan="5">Broader category or group to which the layer belongs within the CLMS portfolio (e.g. Urban Atlas (Priority Area Monitoring); CLCplus (Land Cover and Land Use Mapping))</td>
    </tr>
    <tr>
      <td>Layer category</td>
      <td colspan="5">Categorization of a layer according to its content, purpose, timeliness, level of processing or similar (e.g. status/change/auxiliary/reference layer; near-real time)</td>
    </tr>
    <tr>
      <td>Summary</td>
      <td colspan="5">Brief description of the layer, including the data type (vector), spatial resolution, input data sources, reference dates, and auxiliary features</td>
    </tr>
    <tr>
      <td>Reference year/cycle/period</td>
      <td colspan="5">Specific year, cycle or period that the data represents (e.g. 2018, 2017-2024, days 1-10)</td>
    </tr>
    <tr>
      <td>Geometric resolution</td>
      <td colspan="5">Mapping scale of the vector data (e.g. scale of 1:10 000)</td>
    </tr>
    <tr>
      <td>Coordinate Reference System</td>
      <td colspan="5">Spatial reference system used (e.g. European ETRS89 LAEA projection/national projections)</td>
    </tr>
    <tr>
      <td>Coverage</td>
      <td colspan="5">Geographic area covered by the product area (and reference of EEA coverage) (e.g. EEA-38 + UK)</td>
    </tr>
    <tr>
      <td>Geometric accuracy</td>
      <td colspan="5">Positional accuracy of the product, expressed in meters at a specific % confidence level (e.g. ~11m at 95.5% confidence)</td>
    </tr>
    <tr>
      <td>Thematic accuracy</td>
      <td colspan="5">Accuracy of the thematic classification (according to the target technical requirements), expressed as a percentage for omission and commission errors (e.g. 95% overall accuracy, with omission errors and commission errors not exceeding 15% per class)</td>
    </tr>
    <tr>
      <td>Minimum Mapping Unit</td>
      <td colspan="5">Smallest area that is represented in the product (e.g., 0.5 ha)</td>
    </tr>
    <tr>
      <td>Minimum Mapping Width</td>
      <td colspan="5">Smallest width of features that is represented in the product (e.g., 20 m)</td>
    </tr>
    <tr>
      <td>Vector classes</td>
      <td colspan="5">
        Values assigned to different thematic categories within the vector data<br/>
          11: Very high sealing degree<br/>
          21: Pure needle leaved<br/>
          ...
      </td>    
    </tr>
    <tr>
      <th rowspan="5">Attributes</td>
      <td colspan="5"> Attribute information associated with vector features, including the following minimum fields:</td>
    </tr>
    <tr>
      <td><b>Field</b></td>
      <td><b>Description</b></td>
      <td><b>Type</b></td>
      <td><b>Value(s)</b></td>
      <td><b>NoData value</b></td>
    </tr>
    <tr>
      <td>Shape</td>
      <td>Polygon</td>
      <td>Geometry</td>
      <td>Polygon</td>
      <td></td>
    </tr>
    <tr>
      <td>Shape_Area</td>
      <td>Area</td>
      <td>Double</td>
      <td>0.001 to 1.8E308</td>
      <td></td>
    </tr>
    <tr>
      <td>X_code</td>
      <td>X vector LC class</td>
      <td>Integer</td>
      <td></td>
      <td>254</td>
    </tr>  
    <tr>
      <td>Metadata</td>
      <td colspan="5">Description of the accompanying metadata, including its format and content (e.g. XML metadata files compliant with INSPIRE metadata standards)</td>
    </tr>
    <tr>
      <td>Delivery format</td>
      <td colspan="5">File format in which the layer and ancillary files are delivered (e.g. geopackage, dataset in HDF5, external colour tables in *.lyr and *.lyrx formats)</td>
    </tr>
    <tr>
      <td>Quality -- Production verification</td>
      <td colspan="5">Quality statement of the layer detailing the results of production verification: user's/producer's or/and overall quality of the layer (e.g. layer thematic accuracy reached/exceed the 90% producer's and user's target.)</td>
    </tr>
  </tbody>
</table>
```

:::
{{< pagebreak >}}

:::{.grey-box custom-style="grey-box"}
```{=html}
<table>
  <caption>Table 7.2 Raster product/layer sheet (replace with field 'Layer name')</caption>
  <thead>
    <tr>
      <th>Field</th>
      <th colspan="2">Content description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Layer name</td>
      <td colspan="2">Descriptive name of the layer (e.g. HRL Forest - Tree Cover Density 10m)</td>
    </tr>
    <tr>
      <td>Acronym</td>
      <td colspan="2">Abbreviation or shortened form of the layer name (align with file naming)</td>
    </tr>
    <tr>
      <td>Product (group/family)</td>
      <td colspan="2">Broader category or group to which the layer belongs within the CLMS portfolio (e.g. VLCC/HRL Forest (Land Cover and Land Use Mapping; HR-VPP (Bio-geophysical Parameters)</td>
    </tr>
    <tr>
      <td>Layer category</td>
      <td colspan="2">Categorization of a layer according to its content, purpose, timeliness, level of processing or similar (e.g. status/change/auxiliary/reference layer; near-real time)</td>
    </tr>
    <tr>
      <td>Summary</td>
      <td colspan="2">Brief description of the layer, including the data type (vector), spatial resolution, input data sources, reference dates, and auxiliary features</td>
    </tr>
    <tr>
      <td>Reference year/cycle/period</td>
      <td colspan="2">Specific year, cycle or period that the data represents (e.g. 2018, 2017-2024, days 1-10)</td>
    </tr>
    <tr>
      <td>Geometric resolution</td>
      <td colspan="2">Mapping scale of the vector data (e.g. scale of 1:10 000)</td>
    </tr>
    <tr>
      <td>Coordinate Reference System</td>
      <td colspan="2">Spatial reference system used (e.g. European ETRS89 LAEA projection/national projections)</td>
    </tr>
    <tr>
      <td>Coverage</td>
      <td colspan="2">Geographic area covered by the layer (and reference of EEA coverage) (e.g. EEA-38 + UK)</td>
    </tr>
    <tr>
      <td>Geometric accuracy</td>
      <td colspan="2">Positional accuracy of the layer, expressed in meters at a specific % confidence level (e.g. ~11m at 95.5% confidence)</td>
    </tr>
    <tr>
      <td>Thematic accuracy</td>
      <td colspan="2">Accuracy of the thematic classification (according to the target technical requirements), expressed as a percentage for omission and commission errors (e.g. 95% overall accuracy, with omission errors and commission errors not exceeding 15% per class)</td>
    </tr>
    <tr>
      <td>Minimum Mapping Unit (MMU)</td>
      <td colspan="2">Smallest area that is represented in the layer (e.g. 0.5 ha (50 pixels))</td>
    </tr>
    <tr>
      <td>Raster coding</td>
      <td colspan="2">
        Values assigned to different thematic categories within the raster data
          0: all non-tree covered areas<br/>
          1-100: tree cover density %<br/>
          ...
      </td>    
    </tr>
    <tr>
      <td>Metadata</td>
      <td colspan="2">Description of the accompanying metadata, including its format and content (e.g. XML metadata files compliant with INSPIRE metadata standards)</td>
    </tr>
    <tr>
      <td>Delivery format</td>
      <td colspan="2">File format in which layer is delivered (e.g. GeoTiff)</td>
    </tr>
    <tr>
      <td>Quality - Production verification</td>
      <td colspan="2">Quality statement of the layer detailing the results of production verification: user's/producer's or/and overall quality of the layer (e.g. layer thematic accuracy reached/exceed the 90% producer's and user's target.)</td>
    </tr>
  </tbody>
</table>
```
:::
{{< pagebreak >}}

## Known thematic overlaps of the product [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Provides guidance to assist users in selecting the most appropriate dataset when thematic overlaps exist between CLMS products and known external datasets. The guidance can outline criteria for choosing the best product based on factors such as:

-   Temporal and spatial resolution

-   Data accuracy and validation

-   Data harmonization and interoperability

A few illustrative use cases can help users to recognize where they might encounter thematic overlaps. Additionally, introducing a simple decision tree can help guide users through the process of evaluating overlapping datasets, addressing questions such as whether higher spatial resolution is required, the need for the most recent data, and whether the dataset includes the necessary thematic classes.
:::
{{< pagebreak >}}

# Production methodology and workflow overview [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Summary of the production workflow, input data, production methodology, strengths, and known issues. This chapter serves as a concise overview and should not exceed two pages. For detailed information, please refer to the corresponding ATBD document.
:::

{{< pagebreak >}}

# Terms of use and product technical support [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents information on the terms of use, citation guidelines, and technical support for the products.
:::

## Terms of use [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents information on the legal use of data for added products or derivative works.

Here an example of a standard text.
:::

:::{.grey-box custom-style="grey-box"}
The Terms of Use for the product(s) described in this document, acknowledge the following:

Free, full and open access to the products and services of the Copernicus Land Monitoring Service is made on the conditions that:

1.  When distributing or communicating Copernicus Land Monitoring Service products and services (data, software scripts, web services, user and methodological documentation and similar) to the public, users shall inform the public of the source of these products and services and shall acknowledge that the Copernicus Land Monitoring Service products and services were produced "with funding by the European Union".

2.  Where the Copernicus Land Monitoring Service products and services have been adapted or modified by the user, the user shall clearly state this.

3.  Users shall make sure not to convey the impression to the public that the user\'s activities are officially endorsed by the European Union.

The user has all intellectual property rights to the products he/she has created based on the Copernicus Land Monitoring Service products and services.

[Copernicus Land Monitoring Service - Data policy](https://land.copernicus.eu/en/data-policy){target=_blank}

:::


## Citation [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents guidelines on how to properly cite and reference the products and services of the CLMS.

Here are examples of standard text to be used according to the situation:
:::

:::{.grey-box custom-style="grey-box"}
When **planning to publish a publication (scientific, commercial, etc.)**, it shall explicitly mention:

> "This publication has been prepared using European Union\'s Copernicus Land Monitoring Service information; \<insert all relevant DOI links here, if applicable\>"

When developing a **product or service using the products or services of the Copernicus Land Monitoring Service**, it should shall explicitly mention:

> "Generated using European Union\'s Copernicus Land Monitoring Service information; \<insert all relevant DOI links here, if applicable\>"

When **redistributing a part of the Copernicus Land Monitoring Service (product, dataset, documentation, picture, web service, etc.)**, it shall explicitly mention:

> "European Union\'s Copernicus Land Monitoring Service information; \<insert all relevant DOI links here, if applicable\>"
:::

[Copernicus Land Monitoring Service - Data policy](https://land.copernicus.eu/en/data-policy){target=_blank}

## Product Technical support [(mandatory subchapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents information on the support available for users of the product, including contact details.

Here an example of a standard text.
:::

:::{.greyw-box custom-style="grey-box"}
Product technical support is provided by the product custodian through 
[Copernicus Land Monitoring Service -- Service desk](https://land.copernicus.eu/en/data-policy){target=_blank}.
Product technical support does not include software specific user support or general GIS or remote sensing support.

More information on the products can be found on the Copernicus Land Monitoring Service website (https://land.copernicus.eu/)
:::

{{< pagebreak >}}

# Glossary [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Presents a list of specialized or technical terms used within the document.
:::

{{< pagebreak >}}

# List of abbreviations & acronyms [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Lists abbreviations and acronyms used throughout the document.
:::

:::{.grey-box custom-style="yellow-box"}

  ------------------------------------------------------------------------------
  Abbreviation    Name                                   Reference
  --------------- -------------------------------------- -----------------------
  ATBD            Algorithm Theoretical Basis Document   

  CLMS            Copernicus Land Monitoring Service     land.copernicus.eu

  EEA             European Environment Agency            www.eea.europa.eu

  PUM             Product User Manual                    
  ------------------------------------------------------------------------------

:::  
{{< pagebreak >}}

# References [(mandatory chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Lists references cited throughout the document.
:::

{{< pagebreak >}}

# FAQ\'s [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Lists of frequently asked questions.
:::

{{< pagebreak >}}

# Annexes [(optional chapter)]{.yellow-box custom-style="yellow-box-line"}

:::{.yellow-box custom-style="yellow-box"}
Annexes should be kept to a minimum but can be placed as needed to present essential technical details for the PUM, including naming conventions, file naming nomenclature, download content, coordinate reference systems, colour palettes, aggregation rules, and accuracy metrics.

Limit the number of annexes to what is most relevant for the PUM, ensuring they focus on essential technical details.
:::
