name: Auto Title PRs

on:
  pull_request:
    types: [opened]
    branches:
      - test
      - main

jobs:
  auto_title:
    runs-on: ubuntu-latest
    steps:
      - name: Generate PR Title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const base = pr.base.ref;
            const head = pr.head.ref;
            const type = base === 'test' ? 'feat' : 'chore';
            const title = `${type}(merge): ${head} → ${base}`;

            console.log(`Setting PR title to: ${title}`);

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              title: title
            });
