name: Auto Merge Approved PRs

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved' &&
      (github.event.pull_request.base.ref == 'test' || github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR title
        id: title
        run: |
          title=$(gh pr view ${{ github.event.pull_request.number }} --json title -q .title)
          echo "title=$title" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge the PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --squash \
            --subject "${{ steps.title.outputs.title }}"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
