name: Merge External Publish

on:
  repository_dispatch:
    types: [subtree-published]

jobs:
  merge_external_publish:
    if: startsWith(github.event.client_payload.branch, 'publish-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}
          fetch-depth: 0

      - name: Restore needed merge scripts from main
        run: |
          git fetch origin main
          git checkout origin/main -- .github/scripts
          git reset HEAD .github/scripts

      - name: Set GITHUB_REF_NAME for compatibility
        run: echo "GITHUB_REF_NAME=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

      - name: Setup (before script)
        run: bash .github/scripts/external_publish_before.sh | tee -a job.log

      - name: Merge publish content
        run: bash .github/scripts/external_publish_main.sh | tee -a job.log

      - name: Cleanup
        run: |
          bash .github/scripts/external_publish_after.sh || true
          #bash .github/scripts/external_publish_report_failure.sh || true
