name: Validate

on:
  push:
    branches:
      - develop

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - test
      - main

  workflow_run:
    workflows: ["auto_title"]
    types:
      - completed

jobs:
  validate_pr_title:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: node:23
    steps:
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Validate PR title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "🔍 Validating pull request title..."
          echo "PR Title: $TITLE"
          if [[ ! "$TITLE" =~ ^(feat|fix|chore|docs|style|refactor|perf|test)(\([a-z0-9-]+\))?:\  ]]; then
            echo "❌ Title does not follow Conventional Commits."
            exit 1
          fi
          echo "✅ Title is valid."

  validate_merge_origin:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR base and head
        run: |
          echo "🔍 Validating PR from '${{ github.head_ref }}' to '${{ github.base_ref }}'..."
          ALLOWED=false

          if [[ "${{ github.base_ref }}" == "test" && "${{ github.head_ref }}" == "develop" ]]; then
            ALLOWED=true
          elif [[ "${{ github.base_ref }}" == "main" && "${{ github.head_ref }}" == "test" ]]; then
            ALLOWED=true
          fi

          if [[ "$ALLOWED" != "true" ]]; then
            echo "❌ Invalid PR direction. Only allow:"
            echo "   develop → test"
            echo "   test → main"
            exit 1
          fi

          echo "✅ PR direction is valid."

  notify_failure:
    if: failure() && github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Report failure if publish-* merge
        run: bash .github/scripts/report-failure.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
