name: Validate

on:
  push:
    branches:
      - develop
      - test
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["auto_title"]
    types:
      - completed

jobs:
  validate_pr_title:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: node:23
    steps:
      - name: Install jq
        run: apt-get update && apt-get install -y jq
      - name: Validate PR title
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "🔍 Validating pull request title..."
          echo "PR Title: $TITLE"
          if [[ ! "$TITLE" =~ ^(feat|fix|chore|docs|style|refactor|perf|test)(\([a-z0-9-]+\))?:\  ]]; then
            echo "❌ Title does not follow Conventional Commits."
            exit 1
          fi
          echo "✅ Title is valid."

  validate_merge_origin:
    if: github.event_name == 'push' && (github.ref_name == 'test' || github.ref_name == 'main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Validate merge origin
        run: |
          echo "🔍 Validating merge origin into ${{ github.ref_name }}..."
          MERGE_SOURCE_OK=false
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "${{ github.ref_name }}" == "test" ]]; then
            [[ "$COMMIT_MSG" =~ Merge\ branch\ \'develop\'|from\ develop ]] && MERGE_SOURCE_OK=true
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            [[ "$COMMIT_MSG" =~ Merge\ branch\ \'test\'|from\ test ]] && MERGE_SOURCE_OK=true
          fi
          if [[ "$MERGE_SOURCE_OK" != "true" ]]; then
            echo "❌ Invalid merge source. You must only merge:"
            echo "   develop → test"
            echo "   test → main"
            exit 1
          fi
          echo "✅ Merge source is valid."

  notify_failure:
    if: failure() && github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Report failure if publish-* merge
        run: bash .github/scripts/report-failure.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
